common: &default_settings
  license_key: 'd37590e50f88575698b56c3aab713e5bd491afb8'
  app_name: Desks Near Me
  monitor_mode: false
  developer_mode: false
  log_level: info
  ssl: false
  audit_log:
    enabled: false
  capture_params: true
  browser_monitoring:
    attributes:
      enabled: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    explain_enabled: true
    explain_threshold: 0.5
  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: "ActionController::RoutingError,ActiveRecord::RecordNotFound,Listing::NotFound,Location::NotFound,Page::NotFound"
  custom_insights_events:
    enabled: true

development:
  developer_mode: true

test:
  <<: *default_settings

production:
  <<: *default_settings
  monitor_mode: true
