en:
  simple_form:
    "yes": 'Yes'
    "no": 'No'
    required:
      text: 'required'
      mark: '*'
      # You can uncomment the line below if you need to overwrite the whole required html.
      # When using html, text and mark won't be used.
      # html: '<abbr title="required">*</abbr>'
    error_notification:
      default_message: "Please review the problems below:"

    placeholders:
      defaults:
        topic_ids: 'Select Topic'
        project_ids: 'Select Topic'
        group_ids: 'Select Group'
        category_ids: 'Select Category'
        role: 'Select Role'
        group_type_id: 'Select Group Type'
      search:
        search: 'Search'

      activity_feed:
        content: 'What are you working on?'
        topics: 'Select topics'

      comment:
        body: 'Please, leave a comment'

      search_filter:
        sort: 'Sort by:'

      address:
        address: "What’s your nearest city?"
      onboarding:
        short_bio: 'Ex: I’m a IoT advocate and a technology wizard'

      project:
        name: 'Enter the name of your project'
        summary: 'Summarize this project in less than 140 characters'
        description: 'Tell us all about this project'
        Topic: 'Select Topic'
        link_url: 'Link to'
        link_label: 'Text to display'
        add_collaborators: 'Enter email address'
        links:
          url: 'Link to'
          text: 'Text to Display'
          photo: 'Photo'

      group:
        name: 'Enter the name of your group'
        summary: 'Summarize this group in less than 140 characters'
        description: 'Tell us all about this group'
        project_ids: 'Select Project'
        video_url: 'Enter youtube or vimeo URL'
        search_for_member: 'Search for Member'
        new_group_members:
          email: 'Enter e-mail address'
          moderator: 'Can moderate'

      profile:
        bio: 'Describe yourself in less than 140 characters'
        about: 'Tell us all about yourself project'
        location: 'Enter your city'

    labels:
      merchant_account:
        current_address: "Address"
      user:
        current_address: "Address"
      defaults:
        topic_ids: 'Topic'
        category_ids: 'Category'
        seek_collaborators: 'Seeking Collaborators'
        group_type_id: 'Group Type'
      activity_feed:
        topics: 'Select topics'

      search_filter:
        sort: 'Sort by:'
        collaborators: 'Seeking Collaborators'
        options:
          all: "All"
          featured: "Featured"
          people_i_know: "People I Know"
          most_popular: "Most Popular"
          location: "Near Me"
          number_of_projects: "Number of Projects"

      onboarding:
        location: 'Location'
        'follow[]': 'Follow'
        short_bio: 'Short Bio'
        photo: 'Profile Photo'
      address:
        show:
          address: "Location"

      project:
        name: 'Project Name'
        summary: 'Summary'
        description: 'Description'
        topic: 'Topic'
        add_collaborators: 'Add Collaborators'
        seek_collaborators: 'Seeking Collaborators'

      group:
        transactable_type: 'Type'

      photos:
        file: 'Photo'
        is_cover: 'Cover image'

      links:
        url: 'Link to'
        label: 'Label'
        photo: 'Photo'

      profile:
        bio: 'Short Bio'
        about: 'About You'
        avatar: 'Profile Photo'
        cover: 'Cover Image'
        location: 'Location'


      notifications:
        accept_emails: 'Accept Emails'
        group_updates_enabled: 'Group notifications'
        group_updates_enabled_hint: 'You will be notified about group updates like comments or status updates'
        project_updates_enabled: 'Project notifications'
        project_updates_enabled_hint: 'You will be notified about project updates like comments or status updates'

        email_frequency:
          immediately: 'immediately'
          immediately_hint: 'Email me about each update right away'
          weekly: 'weekly'
          weekly_hint: 'Email me updates summary every week'

    hints:
      project:
        seek_collaborators: 'You can add people to help your project'
        photos: 'For best results use images with dimensions 680×546px or crop them after upload.'

      profile:
        cover_image: 'For best results use an image with dimensions 1920×285px or crop it after upload.'
        avatar: 'For best results use a square image with dimensions 200×200px or crop it after upload.'

  search_submit: 'Go'

  helpers:
    submit:
      search:
        submit: 'Go'
      activity_feed:
        submit: 'Post'
      comment:
        submit: 'Post'
      onboarding:
        submit: 'Continue'
